# Generated by Django 5.2.4 on 2025-07-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_patientprofile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='available_days',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='available_days',
            field=models.ManyToManyField(to='users.day'),
        ),
    ]
